version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"   
    environment:
      - DB_HOST=db
      - DB_USER=esharkova
      - DB_PASSWORD=esharkova
      - DB_NAME=tasks      
      - DB_PORT=5432
    restart: unless-stopped  

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: esharkova
      POSTGRES_DB: tasks
      POSTGRES_PASSWORD: esharkova
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped        

volumes:
  pgdata: