// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Task struct {
	Taskid             int32
	TaskNumber         string
	Description        sql.NullString
	CreateDatetime     time.Time
	CompletionDatetime sql.NullTime
	Priority           sql.NullInt32
}

type User struct {
	Userid         int32
	Firstname      string
	Lastname       string
	PassportNumber string
}
