// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (task_number, description, create_datetime, completion_datetime, priority) VALUES ($1, $2, $3, $4, $5) RETURNING taskid
`

type CreateTaskParams struct {
	TaskNumber         string
	Description        sql.NullString
	CreateDatetime     time.Time
	CompletionDatetime sql.NullTime
	Priority           sql.NullInt32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.TaskNumber,
		arg.Description,
		arg.CreateDatetime,
		arg.CompletionDatetime,
		arg.Priority,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (firstname, lastname, passport_number) VALUES ($1, $2, $3) RETURNING userid
`

type CreateUserParams struct {
	Firstname      string
	Lastname       string
	PassportNumber string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Firstname, arg.Lastname, arg.PassportNumber)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE taskid = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskid int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, taskid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE userid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userid int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userid)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT taskid, task_number, description, create_datetime, completion_datetime, priority FROM tasks WHERE taskid = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, taskid int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, taskid)
	var i Task
	err := row.Scan(
		&i.Taskid,
		&i.TaskNumber,
		&i.Description,
		&i.CreateDatetime,
		&i.CompletionDatetime,
		&i.Priority,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT userid, firstname, lastname, passport_number FROM users WHERE userid = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userid int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.PassportNumber,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT taskid, task_number, description, create_datetime, completion_datetime, priority FROM tasks ORDER BY task_number
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.Taskid,
			&i.TaskNumber,
			&i.Description,
			&i.CreateDatetime,
			&i.CompletionDatetime,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT userid, firstname, lastname, passport_number FROM users ORDER BY lastname
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.PassportNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  task_number = $2,
  description = $3,
  priority = $4
WHERE taskid = $1
RETURNING
  taskid,
  task_number,
  description,
  create_datetime,
  completion_datetime,
  priority
`

type UpdateTaskParams struct {
	Taskid      int32
	TaskNumber  string
	Description sql.NullString
	Priority    sql.NullInt32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Taskid,
		arg.TaskNumber,
		arg.Description,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.Taskid,
		&i.TaskNumber,
		&i.Description,
		&i.CreateDatetime,
		&i.CompletionDatetime,
		&i.Priority,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  firstname = $2,
  lastname = $3
WHERE userid = $1
RETURNING
  userid,
  firstname,
  lastname,
  passport_number
`

type UpdateUserParams struct {
	Userid    int32
	Firstname string
	Lastname  string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Userid, arg.Firstname, arg.Lastname)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.PassportNumber,
	)
	return i, err
}
