// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteTask(ctx context.Context, taskid int32) error
	DeleteUser(ctx context.Context, userid int32) error
	GetTaskByID(ctx context.Context, taskid int32) (Task, error)
	GetUserByID(ctx context.Context, userid int32) (User, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
