// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	task "TaskManagement/internal/model/task"
	user "TaskManagement/internal/model/user"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockuseCase) CreateTask(context context.Context, args task.CreateTaskRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", context, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockuseCaseMockRecorder) CreateTask(context, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockuseCase)(nil).CreateTask), context, args)
}

// CreateUser mocks base method.
func (m *MockuseCase) CreateUser(ontext context.Context, args user.CreateUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ontext, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockuseCaseMockRecorder) CreateUser(ontext, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockuseCase)(nil).CreateUser), ontext, args)
}

// DeleteTask mocks base method.
func (m *MockuseCase) DeleteTask(context context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", context, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockuseCaseMockRecorder) DeleteTask(context, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockuseCase)(nil).DeleteTask), context, id)
}

// DeleteUser mocks base method.
func (m *MockuseCase) DeleteUser(context context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", context, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockuseCaseMockRecorder) DeleteUser(context, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockuseCase)(nil).DeleteUser), context, id)
}

// GetTask mocks base method.
func (m *MockuseCase) GetTask(id int) (task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", id)
	ret0, _ := ret[0].(task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockuseCaseMockRecorder) GetTask(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockuseCase)(nil).GetTask), id)
}

// GetTasks mocks base method.
func (m *MockuseCase) GetTasks() []*task.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks")
	ret0, _ := ret[0].([]*task.Task)
	return ret0
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockuseCaseMockRecorder) GetTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockuseCase)(nil).GetTasks))
}

// GetUser mocks base method.
func (m *MockuseCase) GetUser(id int) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", id)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockuseCaseMockRecorder) GetUser(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockuseCase)(nil).GetUser), id)
}

// GetUsers mocks base method.
func (m *MockuseCase) GetUsers() []*user.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers")
	ret0, _ := ret[0].([]*user.User)
	return ret0
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockuseCaseMockRecorder) GetUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockuseCase)(nil).GetUsers))
}

// UpdateTask mocks base method.
func (m *MockuseCase) UpdateTask(context context.Context, args task.UpdateTaskRequest, id int) (task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", context, args, id)
	ret0, _ := ret[0].(task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockuseCaseMockRecorder) UpdateTask(context, args, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockuseCase)(nil).UpdateTask), context, args, id)
}

// UpdateUser mocks base method.
func (m *MockuseCase) UpdateUser(context context.Context, args user.UpdateUserRequest, id int) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", context, args, id)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockuseCaseMockRecorder) UpdateUser(context, args, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockuseCase)(nil).UpdateUser), context, args, id)
}
